src/Corvus/AdminBundle/Entity/Skills.php
<?php

// src/Corvus/AdminBundle/Entity/Skills.php
namespace Corvus\AdminBundle\Entity;

use Doctrine\ORM\Mapping as ORM,

    Symfony\Component\Validator\Constraints as Assert,

    Corvus\CoreBundle\Entity\TableViewEntity;


/**
 * Corvus\AdminBundle\Entity\Skills
 * 
 * @ORM\Entity(repositoryClass="Corvus\AdminBundle\Entity\SkillsRepository")
 * @ORM\Table
 */
class Skills extends TableViewEntity
{
    // Entity Name is needed to use Late static binding with TableViewEntity
    const ENTITY_NAME   = 'Skills';
    const ROUTE_STEM    = 'skills';


    /**
     * @ORM\Column(type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @ORM\Column(type="string")
     * 
     * @Assert\NotNull()
     * @Assert\Type(type="string")
     * @Assert\Length(max=255)
     */
    private $skill_name;

    /**
     * @ORM\Column(type="string", nullable=true)
     * 
     * @Assert\Type(type="string")
     * @Assert\Length(max=255)
     */
    private $competency;

    /**
     * @ORM\Column(type="decimal", nullable=true)
     */
    private $years_experience;

    /**
     * @ORM\Column(type="text", nullable=true)
     * 
     * @Assert\Type(type="string")
     * @Assert\Length(max=2500)
     */
    private $description;

    /**
     * @ORM\Column(type="boolean")
     * 
     * @Assert\Type(type="bool")
     */
    private $can_display_skill;

    /**
     * @ORM\Column(type="boolean")
     * 
     * @Assert\Type(type="bool")
     */
    private $is_quick_skill;


    public function __construct()
    {
        parent::__construct();
    }

    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set skill_name
     *
     * @param string $skill_name
     */
    public function setSkillName($skill_name)
    {
        $this->skill_name = $skill_name;
    }

    /**
     * Get skill_name
     *
     * @return string 
     */
    public function getSkillName()
    {
        return $this->skill_name;
    }

    /**
     * Set competency
     *
     * @param string $competency
     */
    public function setCompetency($competency)
    {
        $this->competency = $competency;
    }

    /**
     * Get competency
     *
     * @return string 
     */
    public function getCompetency()
    {
        return $this->competency;
    }

    /**
     * Set years_experience
     *
     * @param decimal $years_experience
     */
    public function setYearsExperience($years_experience)
    {
        $this->years_experience = $years_experience;
    }

    /**
     * Get years_experience
     *
     * @return decimal 
     */
    public function getYearsExperience()
    {
        return $this->years_experience;
    }

    /**
     * Set description
     *
     * @param string $description
     */
    public function setDescription($description)
    {
        $this->description = $description;
    }

    /**
     * Get description
     *
     * @return string 
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Set can_display_skill
     *
     * @param boolean $canDisplaySkill
     */
    public function setCanDisplaySkill($canDisplaySkill)
    {
        $this->can_display_skill = $canDisplaySkill;
    }

    /**
     * Get can_display_skill
     *
     * @return boolean 
     */
    public function getCanDisplaySkill()
    {
        return $this->can_display_skill;
    }
    
    /**
     * Set is_quick_skill
     *
     * @param boolean $isQuickSkill
     */
    public function setIsQuickSkill($isQuickSkill)
    {
        $this->is_quick_skill = $isQuickSkill;
    }

    /**
     * Get is_quick_skill
     *
     * @return boolean 
     */
    public function getIsQuickSkill()
    {
        return $this->is_quick_skill;
    }
}

src/Corvus/AdminBundle/Controller/DefaultController.php
<?php

// src/Corvus/AdminBundle/Controller/DefaultController.php
namespace Corvus\AdminBundle\Controller;

use Symfony\Component\HttpFoundation\Request,
    Symfony\Bundle\FrameworkBundle\Controller\Controller,
    Sensio\Bundle\FrameworkExtraBundle\Configuration\Template,
    Sensio\Bundle\FrameworkExtraBundle\Configuration\Route,
    Sensio\Bundle\FrameworkExtraBundle\Configuration\Method,

    Corvus\AdminBundle\Entity\EducationTableView,
    Corvus\AdminBundle\Entity\ProjectHistoryTableView,
    Corvus\AdminBundle\Entity\WorkHistoryTableView,
    Corvus\AdminBundle\Entity\SkillsTableView,
    Corvus\AdminBundle\Entity\NavigationTableView,
    Corvus\AdminBundle\Entity\About,

    Corvus\AdminBundle\Form\Type\EducationTableViewType,
    Corvus\AdminBundle\Form\Type\ProjectHistoryTableViewType,
    Corvus\AdminBundle\Form\Type\WorkHistoryTableViewType,
    Corvus\AdminBundle\Form\Type\SkillsTableViewType,
    Corvus\AdminBundle\Form\Type\NavigationTableViewType,
    Corvus\AdminBundle\Form\Type\AboutType;

class DefaultController extends Controller
{
    /**
     * @Route("/", name="admin_home")
     * @Method({"GET"})
     * 
     * @Template
     */
    public function indexAction()
    {
        return $this->render('CorvusAdminBundle:Default:index.html.twig');
    }

    /**
     * @Route("/site-design", name="admin_site_design")
     * @Method({"GET", "POST"})
     * 
     * @Template
     */
    public function siteDesignAction(Request $request)
    {
        $theme = $this->getDoctrine()
            ->getRepository('ILPBootstrapThemeBundle:Theme')
            ->Find(1);

        if ($theme == null) {
            $theme = new \ILP\BootstrapThemeBundle\Entity\Theme();
        }

        $form = $this->createForm('templating', $theme);

        $form->handleRequest($request);

        if ($form->isValid()) {
            $em = $this->getDoctrine()->getManager();

            $em->persist($theme);
            $em->flush();

            // Generate the Theme files, install them to web/bundles/* and dump the assets
            $themeManager = $this->get('ilp_bootstrap_theme.theme_manager');
            if ($form->get('generate_button')->isClicked()) {
                $returnCode = $themeManager->generateTheme();
            } else {
                $returnCode = $themeManager->installTheme();
            }
            
            
            if ($returnCode === 0) { // $returnCode === 0 means success
                $this->get('session')->getFlashBag()->add('notice', json_encode(array(
                    'title'     => 'Theme Choice has been saved',
                    'message'   => 'The theme has also been compiled!',
                    'level'     => 'success'
                )));
            } else {
                $this->get('session')->getFlashBag()->add('notice', json_encode(array(
                    'title'     => 'An error occured selecting/compiling the theme',
                    'level'     => 'danger'
                )));
            }

            return $this->redirect($this->generateUrl('admin_site_design'));
        } else {
            if ($form->isSubmitted()) {
                $this->get('session')->getFlashBag()->add('notice', json_encode(array(
                    'title'     => 'Validation Failed',
                    'message'   => 'Please correct the errors to continue!',
                    'level'     => 'warning'
                )));
            }
        }

        return array(
            'form' => $form->createView(),
        );
    }
    
    /**
     * @Route("/theme-editor", name="admin_theme_editor")
     * @Method({"GET", "POST"})
     * 
     * @Template
     */
    public function themeEditorAction()
    {
        return array();
    }

    /**
     * @Route("/education", name="admin_education")
     * @Method({"GET"})
     * 
     * @Template
     */
    public function educationAction()
    {
        $educationTableView = new EducationTableView();

        $education = $this->getDoctrine()
            ->getRepository('CorvusAdminBundle:Education')
            ->findAll();

        foreach ($education as $edu) {
            $educationTableView->getEducation()->add($edu);
        }

        $form = $this->createForm(new EducationTableViewType(), $educationTableView);

        return array(
            'form' => $form->createView(),
        );
    }

    /**
     * @Route("/project-history", name="admin_project_history")
     * @Method({"GET"})
     * 
     * @Template
     */
    public function projectHistoryAction()
    {
        $projectHistoryTableView = new ProjectHistoryTableView();

        $projectHistory = $this->getDoctrine()
            ->getRepository('CorvusAdminBundle:ProjectHistory')
            ->findAll();

        foreach ($projectHistory as $ph) {
            $projectHistoryTableView->getProjectHistory()->add($ph);
        }

        $form = $this->createForm(new ProjectHistoryTableViewType(), $projectHistoryTableView);

        return array(
            'form' => $form->createView(),
        );
    }

    /**
     * @Route("/work-history", name="admin_work_history")
     * @Method({"GET"})
     * 
     * @Template
     */
    public function workHistoryAction()
    {
        $workHistoryTableView = new WorkHistoryTableView();

        $workHistory = $this->getDoctrine()
            ->getRepository('CorvusAdminBundle:WorkHistory')
            ->findAll();

        foreach ($workHistory as $wh) {
            $workHistoryTableView->getWorkHistory()->add($wh);
        }

        $form = $this->createForm(new WorkHistoryTableViewType(), $workHistoryTableView);

        return array(
            'form' => $form->createView(),
        );
    }

    /**
     * @Route("/skills", name="admin_skills")
     * @Method({"GET"})
     * 
     * @Template
     */
    public function skillsAction()
    {
        $skillsTableView = new SkillsTableView();

        $skills = $this->getDoctrine()
            ->getRepository('CorvusAdminBundle:Skills')
            ->FindAll();

        foreach ($skills as $skill) {
            $skillsTableView->getSkills()->add($skill);
        }

        $form = $this->createForm(new SkillsTableViewType(), $skillsTableView);

        return array(
            'form' => $form->createView(),
        );
    }

    /**
     * @Route("/navigation", name="admin_navigation")
     * @Method({"GET"})
     * 
     * @Template
     */
    public function navigationAction()
    {
        $navigationTableView = new NavigationTableView();

        $navigation = $this->getDoctrine()
            ->getRepository('CorvusAdminBundle:Navigation')
            ->FindAll();

        foreach ($navigation as $navItem) {
            $navigationTableView->getNavItems()->add($navItem);
        }

        $form = $this->createForm(new NavigationTableViewType(), $navigationTableView); 

        return array(
            'form' => $form->createView(),
        );
    }

    /**
     * @Route("/downloads", name="admin_downloads")
     * @Method({"GET"})
     * 
     * @Template
     */
    public function downloadsAction()
    {
        return $this->render('CorvusAdminBundle:Default:downloads.html.twig');
    }

    /**
     * @Route("/about", name="admin_about")
     * @Method({"GET", "POST"})
     * @Template
     * 
     * @param \Symfony\Component\HttpFoundation\Request $request
     */
    public function aboutAction(Request $request)
    {
        $about = $this->getDoctrine()
            ->getRepository('CorvusAdminBundle:About')
            ->Find(1);

        if($about == null) {
            $about = new About();
        }

        $form = $this->createForm(new AboutType(), $about);

        $form->handleRequest($request);

        if ($form->isValid()) {
            $em = $this->getDoctrine()->getManager();

            $em->persist($about);
            $em->flush();

            $this->get('session')->getFlashBag()->add('notice', json_encode(array(
                'title'     => 'Your changes were saved!',
                'level'     => 'success'
            )));
            return $this->redirect($this->generateUrl('admin_about'));
        } else {
            if ($form->isSubmitted()) {
                $this->get('session')->getFlashBag()->add('notice', json_encode(array(
                    'title'     => 'Validation Failed',
                    'message'   => 'Please correct the errors to continue!',
                    'level'     => 'warning'
                )));
            }
        }
        
        return array(
            'form' => $form->createView(),
        );
    }
}

src/Corvus/AdminBundle/Resources/views/Default/adminBase.html.twig
<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}Corvus Dashboard{% endblock %}</title>
	
	<link rel="shortcut icon" href="/favicon.ico" type="image/x-icon" />
	<link rel="apple-touch-icon-precomposed" sizes="152x152" href="/apple-touch-icon-152x152.png" />
	<link rel="apple-touch-icon-precomposed" sizes="144x144" href="/apple-touch-icon-144x144.png" />
	<link rel="apple-touch-icon-precomposed" sizes="120x120" href="/apple-touch-icon-120x120.png" />
	<link rel="apple-touch-icon-precomposed" sizes="114x114" href="/apple-touch-icon-114x114.png" />
	<link rel="apple-touch-icon-precomposed" sizes="76x76" href="/apple-touch-icon-76x76.png" />
	<link rel="apple-touch-icon-precomposed" sizes="72x72" href="/apple-touch-icon-72x72.png" />
	<link rel="apple-touch-icon-precomposed" sizes="57x57" href="/apple-touch-icon-57x57.png" />
	<link rel="apple-touch-icon-precomposed "href="/apple-touch-icon.png" />

	{% stylesheets filter="?cssrewrite"
		'%kernel.root_dir%/../vendor/twbs/bootstrap/less/bootstrap.less'
		'bundles/corvuscore/css/core.less'
		'bundles/corvusadmin/css/layout.less'
		'bundles/corvusadmin/css/layout.css'
        'bundles/corvusadmin/css/design.css'
		'%kernel.root_dir%/Resources/public/css/font-awesome.min.css'
	%}
		<link rel="stylesheet" href="{{ asset_url }}">
	{% endstylesheets %}
    {% block stylesheets %}
    {% endblock %}
</head>
<body>
    {% import 'CorvusCoreBundle:Default:core.html.twig' as core %}
	<nav class="navbar navbar-inverse navbar-static-top" role="navigation" id="corvusBar">
		<div class="navbar-header">
			<a class="navbar-brand" href="{{ path('admin_home') }}">
				<img src="{{ asset('bundles/corvusadmin/images/corvusV2-64.png') }}" class="brandLogo" /> &nbsp; Corvus &nbsp;
				{% if corvus_version %}<sup><small>V. {{ corvus_version }}</small></sup>{% endif %}
			</a>
		</div>

		<ul class="nav navbar-nav navbar-right">
			<li>
				<a href="{{ path('frontend_logout') }}"><i class="fa fa-sign-out"></i> Logout</a>
			</li>
		</ul>
		<p class="navbar-text navbar-right">
			Logged in as {{ portfolio_info.about.firstname }}
		</p>
	</nav>
    <div class="container-fluid">
        <div class="row">
            <navigation class="col-md-2">
                <ul class="nav nav-pills nav-stacked">
                    {{ portfolio_info.createNavItem('admin_home', 'Home', 'Home Link', 'fa-home') }}
                    {{ portfolio_info.createNavStack([
                            'admin_general_settings',
                            'General Settings',
                            'General Settings Link',
                            'fa-cogs'
                        ],
                        [[
                            'admin_general_settings_security',
                            'Account Security',
                            'Account Security Link',
                            'fa-lock'
                        ], [
                            'admin_general_settings_analytics',
                            'Analytics',
                            'Analytics Link',
                            'fa-eye'
                        ]
                        ])
                    }}
                    {{ portfolio_info.createNavItem('admin_site_design', 'Site Design', 'Site Design Link', 'fa-tint') }}
                    {{ portfolio_info.createNavItem('admin_education', 'Education', 'Education Link', 'fa-book') }}
                    {{ portfolio_info.createNavItem('admin_work_history', 'Work History', 'Work History Link', 'fa-briefcase') }}
                    {{ portfolio_info.createNavItem('admin_project_history', 'Project History', 'Project History Link', 'fa-rocket') }}
                    {{ portfolio_info.createNavItem('admin_skills', 'Skills', 'Skills Link', 'fa-magic') }}
                    {{ portfolio_info.createNavItem('admin_navigation', 'Navigation', 'Navigation Link', 'fa-sitemap') }}
                    {{ portfolio_info.createNavItem('admin_downloads', 'Downloads', 'Downloads Link', 'fa-gift') }}
                    {{ portfolio_info.createNavItem('admin_about', 'About', 'About Link', 'fa-user') }}
                </ul>
            </navigation>

            <div class="col-md-10">
                <ol class="breadcrumb">
                    <li><a href="{{ path('admin_home') }}">Home</a></li>
                    {% block breadcrumbs %}{% endblock %}
                </ol>
                {% block mainContent %}

                {% endblock %}
            </div>
        </div>
    </div>

    <footer id="pageFooter">
		<div class="row">
			<div class="col-md-6">
				<ul class="list-fixed no-list">
					<li><i class="fa fa-github"></i> <a href="https://github.com/ilikeprograms/corvus" target="_blank">Github</a> <sup>(View or Fork Corvus)</sup></li>
					<li><i class="fa fa-globe"></i> <a href="http://corvus.ilikeprograms.com" target="_blank">Corvus Website</a></li>
					<li><i class="fa fa-wechat"></i> <a href="irc://irc.freenode.net/corvus" target="_blank">#corvus on irc.freenode</a></li>
					<li><i class="fa fa-envelope"></i> <a href="mailto:%22Corvus%20Support%22%20%3ccorvus-support@ilikeprograms.com%3e?subject=Corvus Support">Send us an Email</a> <sup>(corvus-support@ilikeprograms.com)</sup></li>
					<li><i class="fa fa-stack-overflow"></i> <a href="http://stackoverflow.com/questions/tagged/corvus" target="_blank">Stack Overflow</a></li>
				</ul>
			</div>
			<div class="col-md-6 text-right">
				<ul class="list-fixed no-list">
					<li><i class="fa fa-home"></i> <a href="{{ path('frontend_homepage') }}">View Portfolio</a></li>
					<li><i class="fa fa-arrow-up"></i> <a href="#corvusBar">Back to top</a></li>
				</ul>
			</div>
		</div>
		<p class='text-center'><sub>Corvus is released under the MIT License, see LICENCE.txt under the project root for the full licence.</sub></p>
    </footer>

    <div class="alert alert-dismissable hidden" id='alert-template' aria-hidden="true" tabindex="-1" role="alert">
        <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <strong></strong>
        <p></p>
    </div>

{% javascripts
	'%kernel.root_dir%/Resources/js/jquery.min.js'
	'bundles/corvuscore/js/common.js'
	'bundles/corvuscore/js/core.js'
	'%kernel.root_dir%/../vendor/twbs/bootstrap/js/tab.js'
	'%kernel.root_dir%/../vendor/twbs/bootstrap/js/alert.js'
	'bundles/corvusadmin/js/noticeScript.js'
%}
	<script src="{{ asset_url }}"></script>
{% endjavascripts %}

{% block javascripts %}
{% endblock %}

{% if app.session.flashbag.has('notice') %}
    {{ core.displayNotice(app.session.flashbag.get('notice')[0]) }}
{% endif %}
</body>
</html>

src/Corvus/AdminBundle/Resources/views/Default/editNavigation.html.twig
{% extends 'CorvusAdminBundle:Default:adminBase.html.twig' %}

{% block breadcrumbs %}
	<li><a href="{{ path('admin_navigation') }}">Navigation</a></li>
	<li class="active">Edit</li>
{% endblock %}

{% block mainContent %}
	<h2>Editing "{{ form.vars.value.title }} Link"</h2>
	<p class="well">
		Use this form to update the Navigation item.<br />
		<span class="label label-warning">Dont forget!</span> You can still swap the Navigation between an <b>External/Internal</b> link.
	</p>

	<form role="form" action="{{ path('admin_navigation_edit', {'id' : form.vars.value.id }) }}" method="post" {{ form_enctype(form) }}>
		<fieldset>
			<legend>Navigation Fields:</legend>

            <div class="form-group">
                {{ form_label(form.href) }}
                {{ form_widget(form.href) }}
            </div>

            <div class="form-group">
                {{ form_label(form.title) }}
                {{ form_widget(form.title) }}
            </div>

            <div class="form-group">
                {{ form_label(form.alt) }}
                {{ form_widget(form.alt) }}
            </div>

            <div class="form-group">
                {{ form_label(form.internalRoutes) }}
                {{ form_widget(form.internalRoutes) }}
            </div>

            <p class="help-block">The Internal Routes are pages on the Frontend of the Portfolio</p>
		</fieldset>

		{{ form_rest(form) }}
        {{ core.formErrors(form) }}

		<input type="submit" class="btn btn-primary" value="Save" />	
	</form>

	<aside>
		<h3>Help</h3>
		<p>Fields marked with <span class="required-hint"></span> are required</p>
	</aside>
{% endblock %}

src/Corvus/AdminBundle/Resources/views/Default/editProjectHistory.html.twig
{% extends 'CorvusAdminBundle:Default:adminBase.html.twig' %}

{% block breadcrumbs %}
	<li><a href="{{ path('admin_project_history') }}">Project History</a></li>
	<li class="active">Edit</li>
{% endblock %}

{% block mainContent %}
	<h2>Edit "{{ form.vars.value.projectName }} - {{ form.vars.value.role }}"</h2>
	<p class="well">
        Use this form to update the <b>Project overview.</b>
	</p>

	<form role="form" action="{{ path('admin_project_history_edit', {'id' : form.vars.value.id }) }}" method="post" {{ form_enctype(form) }}>
		<fieldset>
			<legend>Project History Fields:</legend>			 

            <div class="form-group">
                {{ form_label(form.slug) }}
                {{ form_widget(form.slug) }}
            </div>

    		<div class="form-group">
                {{ form_label(form.project_name) }}
                {{ form_widget(form.project_name) }}
            </div>

            <div class="form-group">
                {{ form_label(form.project_description) }}
                {{ form_widget(form.project_description) }}
            </div>

            <div class="form-group">
                {{ form_label(form.role) }}
                {{ form_widget(form.role) }}
            </div>

            <div class="form-group">
                {{ form_label(form.process) }}
                {{ form_widget(form.process) }}
            </div>

            <div class="form-group">
                {{ form_label(form.feedback_received) }}
                {{ form_widget(form.feedback_received) }}
            </div>

            <div class="form-group">
                {{ form_label(form.reflection) }}
                {{ form_widget(form.reflection) }}
            </div>  

            <div class="form-group">
                {{ form_label(form.url) }}
                {{ form_widget(form.url) }}
            </div>

            <div class="form-group">
                {{ form_label(form.is_published) }}
                {{ form_widget(form.is_published) }}
            </div>
		</fieldset>

        <fieldset>
            <legend>Meta Info:</legend>

            <div class="form-group">
                {{ form_label(form.meta_title) }}
                {{ form_widget(form.meta_title) }}
            </div>

            <div class="form-group">
                {{ form_label(form.meta_description) }}
                {{ form_widget(form.meta_description) }}
            </div>
        </fieldset>

		{{ form_row(form._token) }}
        {{ core.formErrors(form) }}
		
		<input type="submit" class="btn btn-primary" value="Save" />
	</form>
	
	<aside>
		<h3>Help</h3>
		<p>Fields marked with <span class="required-hint"></span> are required</p>
	</aside>
{% endblock %}

src/Corvus/AdminBundle/Resources/views/Default/editSkills.html.twig
{% extends 'CorvusAdminBundle:Default:adminBase.html.twig' %}

{% block breadcrumbs %}
	<li><a href="{{ path('admin_skills') }}">Skills</a></li>
	<li class="active">Edit</li>
{% endblock %}

{% block mainContent %}
	<h2>Editing "{{ form.vars.value.skillName }}"</h2>
	<p class="well">
		Use this form to update the <b>Skill details</b>.
	</p>

	<form role="form" action="{{ path('admin_skills_edit', {'id' : form.vars.value.id }) }}" method="post" {{ form_enctype(form) }}>
		<fieldset>
			<legend>Skill Fields:</legend>

			<div class="form-group">
                {{ form_label(form.skill_name) }}
                {{ form_widget(form.skill_name) }}
            </div>

			<div class="form-group">
                {{ form_label(form.competency) }}
                {{ form_widget(form.competency) }}
            </div>

            <div class="form-goup">
                {{ form_label(form.years_experience) }}
                {{ form_widget(form.years_experience) }}
            </div>

            <div class="form-goup">
                {{ form_label(form.description) }}
                {{ form_widget(form.description) }}
            </div>
			
			<div class="form-group">
                {{ form_label(form.can_display_skill) }}
                {{ form_widget(form.can_display_skill) }}
            </div>
			
			<p class="help-block">Controls if <b>All details about the Skill</b> will be displayed</p>
			
			<div class="form-group">
                {{ form_label(form.is_quick_skill) }}
                {{ form_widget(form.is_quick_skill) }}
            </div>
			
			<p class="help-block">Controls if the Skill will be <b>displayed in the Quick Skills</b> section</p>
		</fieldset>

		{{ form_rest(form) }}
        {{ core.formErrors(form) }}

		<input type="submit" class="btn btn-primary" value="Save" />
	</form>
	
	<aside>
		<h3>Help</h3>
		<p>Fields marked with <span class="required-hint"></span> are required</p>
	</aside>
{% endblock %}

src/Corvus/AdminBundle/Resources/views/Default/editWorkHistory.html.twig
{% extends 'CorvusAdminBundle:Default:adminBase.html.twig' %}

{% block breadcrumbs %}
	<li><a href="{{ path('admin_work_history') }}">WorkHistory</a></li>
	<li class="active">Edit</li>
{% endblock %}

{% block mainContent %}
	<h2>Edit "{{ form.vars.value.employerName }} - {{ form.vars.value.role }}"</h2>
	<p class="well">
      Use this form to update the <b>Work Overview</b> for the <b>Employment/Role.</b>
	</p>

	<form role="form" action="{{ path('admin_work_history_edit', {'id' : form.vars.value.id }) }}" method="post" {{ form_enctype(form) }}>
		{{ form_errors(form) }}
		<fieldset>
			<legend>Work History Fields:</legend>

            <div class="form-group">
                {{ form_label(form.slug) }}
                {{ form_widget(form.slug) }}
            </div>

			<div class="form-group">
                {{ form_label(form.employer_name) }}
                {{ form_widget(form.employer_name) }}
            </div>

			<div class="form-group">
                {{ form_label(form.employer_address) }}
                {{ form_widget(form.employer_address) }}
            </div>

			<div class="form-group">
                {{ form_label(form.start_date) }}
                {{ form_widget(form.start_date) }}
            </div>
            
			<div class="form-group">
                {{ form_label(form.end_date) }}
                {{ form_widget(form.end_date) }}
            </div>
			
			<div class="form-group">
                {{ form_label(form.is_current_position) }}
                {{ form_widget(form.is_current_position) }}
            </div>

			<div class="form-group">
                {{ form_label(form.role) }}
                {{ form_widget(form.role) }}
            </div>

            <div class="form-group">
                {{ form_label(form.duties) }}
                {{ form_widget(form.duties) }}
            </div>

            <div class="form-group">
                {{ form_label(form.feedback_received) }}
                {{ form_widget(form.feedback_received) }}
            </div>

            <div class="form-group">
                {{ form_label(form.reflection) }}
                {{ form_widget(form.reflection) }}
            </div>

            <div class="form-group">
                {{ form_label(form.employer_phone_number) }}
                {{ form_widget(form.employer_phone_number) }}
            </div>

            <div class="form-group">
                {{ form_label(form.is_published) }}
                {{ form_widget(form.is_published) }}
            </div>
		</fieldset>

		<fieldset>
            <legend>Meta Info:</legend>

            <div class="form-group">
                {{ form_label(form.meta_title) }}
                {{ form_widget(form.meta_title) }}
            </div>

            <div class="form-group">
                {{ form_label(form.meta_description) }}
                {{ form_widget(form.meta_description) }}
            </div>
        </fieldset>

    	{{ form_rest(form) }}
        {{ core.formErrors(form) }}

		<input type="submit" class="btn btn-primary" value="Save" />
	</form>
	
	<aside>
		<h3>Help</h3>
		<p>Fields marked with <span class="required-hint"></span> are required</p>
	</aside>
{% endblock %}

{% block javascripts %}<script src="{{ asset('bundles/corvusadmin/js/workhistory.js') }}"></script>{% endblock %}